apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-config
  labels:
    app: {{ include "spring-boot-api.name" . }}
data:
  config.json: |
    {
      "key1": "value1",
      "key2": "value2",
      "key3": "value3"
    }