apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: spring-boot-api
        url: https://kubernetes.default.svc
      - cluster: spring-boot-api-prod
        url: gke_gcp-1-431611_us-central1-a_prd-global-cluster-5
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: development
      source:
        repoURL: https://github.com/dimaserbenyuk/GCP
        targetRevision: HEAD
        path: k8s/helm/env/dev/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: guestbook