{{- $username := randAlphaNum 8 | b64enc -}}
{{- $password := randAlphaNum 16 | b64enc -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  labels:
    app: {{ include "spring-boot-api.name" . }}
type: Opaque
data:
  username: {{ $username }}
  password: {{ $password }}
